### PR TITLE
RemoveAppointmentFromPetCommand + Storage integration

### PR DESCRIPTION
**Pull request by md-azsa**
2 Features in 1 PR! Great Deal! Great Bugs!
Fixes issue #17 

## **Features added:** 😄 
- RemoveAppointmentFromPetCommand is working
> Removes an appointment from a pet given the index of the last listing of appointment.
- Appointment in storage now holds the ClientOwnPet class and stores it in the XML
> Any changes made will be reflected in the XML file
> `removeapptfrompet` & `addappttopet` will reflect those changes
- `removeapptfrompet` command is now inside auto-complete
> Planning to add command aliases because the commands are too long.

## **Currently doing.** 🤕 
- Adding test cases for the new commands added.
- Adding alias for `removeapptfrompet` and `addappttopet` commands.
~~- Update UserGuide.adoc to acknowledge the commands.~~

## **Known issues with this PR** 😭 `FIXED`
-  Undo/redo command strangely doesn't work on `removeapptfrompet` & `addappttopet`
> Throws a weird error on logic component regarding UndoableCommand
> I suspect it might be the storage component
> _Bad work around through this problem_
> Make both AddAppointmentToPet and RemoveAppointmentFromPet command non-undoable.
> Constraint users to only doing these commands to remove and add appointments i.e. no undo/redo

### CODE REVIEW

**Comment by hzxcaryn** [comment]
Coverage failed, please don't merge before settling the issue.

**Comment by md-azsa** [comment]
@hzxcaryn Thank you for the kind notice. We are working on it now. Please do keep in touch for future developments. Please be patient.

**Comment by jonathanwj** [comment]
AddressBook#resetData() method needs to return a deep copy of the appointmentlist, it is currently returning a shallow copy.
The UndoableCommand#saveAddressBookSnapshot() method will save the previousAddressBook by using the resetData() method. 
If a shallow copy is returned, the changes in the current AddressBook will also reflect on the previousAddressBook. Thus being unable to undo as the previousAddressBook already the same as the current AddressBook.

Fix:
1) Create a new appointment object when resetting the data
image

2) AddressBook#addAppointmentToPet() also has to be modified. 
As the redo command executes from the previous executed command, the appointment object will have contain the added ClientOwnPet object from the execution and the appointment.getClientOwnPet() will never be null.
image

**Comment by md-azsa** [comment]
@jonathanwj 
## Fix for known issues
Thank you Jonathan! Fixed the issue.
Similar issue came up with `removeapptfrompet` command when doing undo/redo.

Thank you very much for pointing out the mistake! 😄

**Comment by md-azsa** [comment]
Solved

**Pull request merged**
